In [281]:
import numpy as np

In [282]:
print(np.__version__)

2.3.3


In [287]:
## print("welcome to the Numpy Analyzer!")
print("======================================")
while True:
    print("\nchoose an option:")
    print("1. Create a Numpy array")
    print("2. Perform a Mathematical Operation")
    print("3. Combine or split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")
    

    ch = int(input("Enter your choice:"))

    if ch == 1:
        num_array()

    elif ch == 2:
        math_operation()

    elif ch == 3:
        combine()

    elif ch == 4:
        search_sort_filter()
        
    elif ch == 5:
        aggr()

    elif ch == 6:
        print("\nExiting the sysytem. All resources have been freed.")
        print("Goodbye!👋👋👋")
        break       
        
    else:
        print("Invalid choice. Please try again🤦.\n")
        break    

#-----------------start coding---------------
def num_array():
    print("\nselect the type of array to create:")
    print("===========================================")
    while True:
        print("\n1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")

        ch = int(input("\nEnter Your choice:"))

        if ch == 1:

            element = list(map(int, input("\nEnter elements for the array seperated by space:").split()))
            arr = np.array(element) 
            print("\n1D Array created successfully:")
            print(arr) 
            
        elif ch == 2:
            r = int(input("\nEnter a number of rows:"))
            c = int(input("Enter a number of columns:"))
            element = list(map(int, input(f"\nEnter {r*c} elements for the array seperated by space:").split()))
            arr = np.array(element).reshape(r,c)
            print("\n2D Array Created Successfully:")
            print(arr)

        elif ch == 3:
            d = int(input("\nEnter depth: "))
            r = int(input("Enter a number of rows:"))
            c = int(input("Enter a number of columns:"))
            element = list(map(int, input(f"\nEnter {d*r*c} elements for the array seperated by space:").split()))
            arr = np.array(element).reshape(d,r,c)
            print("\n3D Array Created Successfully:")
            print(arr)
            
    
            print("\nchoose an operation:")
            print("1. Indexing")
            print("2. Slicing")
        
            ch = int(input("\nEnter a choice:"))


            if ch == 1:
                if arr.ndim == 1:
                    indx = int(input("\nEnter index"))
                    print("Element", arr[indx])

                elif arr.ndim == 2:
                    row_index = int(input("\nEnter row index:"))
                    col_index = int(input("Enter col index:"))
                    print("Element", arr[arr[row_index, col_index]])

                elif arr.ndim == 3:
                    dpt = int(input("\nEnter depth index:"))
                    row_index = int(input("Enter row index:"))
                    col_index = int(input("Enter col index:"))
                    print("Element:", arr[dpt, row_index, col_index])

            elif ch == 2:
                row_start, row_stop = map(int, input("\nEnter the row range(start:end):").split(":")) 
                col_start, col_stop = map(int, input("Enter the column range(start:end):").split(":")) 
                print(arr[row_start : row_stop, col_start : col_stop])
                break
                
            else:
                print("choose correct option🤦")
            break


                


def math_operation():
    while True:
        print("\nMathematical operation")
        print("===================================")
        first_array = np.array(list(map(int, input("\nEnter the elements for 1st array:").split())))
        print(np.array(first_array))
            
        second_array = np.array(list(map(int, input("Enter the elements for 2nd array:").split())))
        print(np.array(second_array))
        
        print("\nchoose a mathematical opearation")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        
        ch = int(input("\nChoose a choice:"))

        if ch == 1:
            print("\naddition is:", first_array + second_array)
            
        elif ch == 2:
            print("\nsubtraction is:", first_array - second_array)

        elif ch == 3:
            print("\nmultiplication is:", first_array * second_array)

        elif ch == 4:
            print("\ndivision is:", first_array / second_array)
        else:
            print("choose correct option🤦")
        break


def combine():
    print("\ncombine or split arrays")
    print("===================================")
    while True:
        print("1. Combine array")
        print("2. Split array")

        ch = int(input("Enter a choice: "))

        if ch == 1:
            first_array = list(map(int, input("Enter elements for 1st array:").split()))
            print(first_array)

            second_array = list(map(int, input("Enter elements for 2nd array:").split()))
            print(second_array)

            print("Combine array is:", first_array + second_array)

        elif ch == 2:
            arr = list(map(int, input("Enter elements:").split()))
            print("array:-", arr)

            n = int(input("\nEnter index to split:"))

            first_list = arr[:n]
            last_list = arr[n:]

            print("\nfirst_list", first_list)
            print("last_list",last_list)
        else:
            print("choose correct option🤦")

        break


def search_sort_filter():
    while True:

        arr = list(map(int, input("\nEnter elements:").split()))
        print(arr) 
        
        print("\nchoose an option:")
        
        print("1. Search a value")
        print("2. sort the array")
        print("3. filter value")

        ch = int(input("choose an options:"))


        if ch == 1:  # search a value
            
            val = int(input("\nEnter number to search:"))

            if val in arr:
                print(val, "found at index", arr.index(val))
            else:
                print(val, "not found")

        elif ch == 2:  #sort the array
            
            arr.sort()
            print("\nElements in ascending order: ",arr)

            arr.sort(reverse = True)
            print("Elements in descending order: ",arr)

        elif ch == 3:   # filter value
            
            even = [x for x in arr if x%2 == 0]
            print("\nEven number is:", even)

            odd = [x for x in arr if x%2!= 0]
            print("Odd number is:", odd)

            y = int(input("\nEnter the value"))

            grtr = [x for x in arr if x > y]
            print(f"\nthe value which is greater then {y}:", grtr)
            

        else:
            print("choose correct option🤦")
            search_sort_filter()
        break



        
def aggr():
    while True:
        print("\naggregate/statistical operations:")
        print("=========================================")
        arr = list(map(int, input("Enter elements:").split()))
        print(arr)
        print("\nchoose an operations:")
        print("1. Sum")
        print("2. Mean")
        print("3. Median")
        print("4. Standard Deviation")
        print("5. Varianve")

       
        ch = int(input("choose an option:"))

        if ch == 1:
            print("Sum is:", np.sum(arr))
        elif ch == 2:
            print("Mean is:", np.mean(arr))
        elif ch == 3:
            print("Median is", np.median(arr))
        elif ch == 4:
            print("Standard Deviation is:", np.std(arr))
        elif ch == 5:
            print("Variance is:", np.var(arr))
        else:
            print("choose correct option🤦")
            aggr()
        break
    

        
# num_array()
# math_operation()
# combine()
# search_sort_filter()
# aggr()

    


choose an option:
1. Create a Numpy array
2. Perform a Mathematical Operation
3. Combine or split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice: 1



select the type of array to create:

1. 1D Array
2. 2D Array
3. 3D Array



Enter Your choice: 3

Enter depth:  2
Enter a number of rows: 3
Enter a number of columns: 1

Enter 6 elements for the array seperated by space: 1 2 3 4 5 6



3D Array Created Successfully:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

choose an operation:
1. Indexing
2. Slicing



Enter a choice: 2

Enter the row range(start:end): 0:1
Enter the column range(start:end): 1:0


[]

choose an option:
1. Create a Numpy array
2. Perform a Mathematical Operation
3. Combine or split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice: 2



Mathematical operation



Enter the elements for 1st array: 2 4 5


[2 4 5]


Enter the elements for 2nd array: 6 5 3


[6 5 3]

choose a mathematical opearation
1. Addition
2. Subtraction
3. Multiplication
4. Division



Choose a choice: 4



division is: [0.33333333 0.8        1.66666667]

choose an option:
1. Create a Numpy array
2. Perform a Mathematical Operation
3. Combine or split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice: 3



combine or split arrays
1. Combine array
2. Split array


Enter a choice:  1
Enter elements for 1st array: 14 5 7


[14, 5, 7]


Enter elements for 2nd array: 5 3 2


[5, 3, 2]
Combine array is: [14, 5, 7, 5, 3, 2]

choose an option:
1. Create a Numpy array
2. Perform a Mathematical Operation
3. Combine or split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice: 4

Enter elements: 5 7 8 4 


[5, 7, 8, 4]

choose an option:
1. Search a value
2. sort the array
3. filter value


choose an options: 2



Elements in ascending order:  [4, 5, 7, 8]
Elements in descending order:  [8, 7, 5, 4]

choose an option:
1. Create a Numpy array
2. Perform a Mathematical Operation
3. Combine or split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice: 5



aggregate/statistical operations:


Enter elements: 6 4 7 5 7


[6, 4, 7, 5, 7]

choose an operations:
1. Sum
2. Mean
3. Median
4. Standard Deviation
5. Varianve


choose an option: 2


Mean is: 5.8

choose an option:
1. Create a Numpy array
2. Perform a Mathematical Operation
3. Combine or split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice: 8


Invalid choice. Please try again🤦.

